### PR TITLE
Don’t run fabric script until APIKey is provided template

### PR DESCRIPTION
**Pull request by heyltsjay**

### CODE REVIEW

**Comment by heyltsjay** [comment]
@KingOfBrian bump

**Comment by heyltsjay** [comment]
actually i guess i never tagged you

**Comment by heyltsjay** [comment]
soooo `length == 40`? is the api key length fixed?

**Comment by heyltsjay** [comment]
@KingOfBrian can we close the loop on this one?  What length check would make you feel better?

**Comment by KingOfBrian** [comment]
Sorry for the delay! It's pretty static so I guess it won't be a real problem, so LGTM!

**Pull request merged**
